### ISSUE TITLE
Omit without when

### ISSUE THREAD

**Issue by vonagam** [ealush/vest#1071]
I am writing a utility for working with forms/vest. Inputs in html can be marked as disabled or readonly. By specification such inputs do not participate in validation. I want to provide a way for a user to toggle those states for arbitrary fields and match behaviour of vest suite with html specification.

There is `omitWhen` which does what I need but to utilize it I would need to wrap every `test` call with `omitWhen`. I can write a wrapper for `test` and ask user to use it. But I would prefer to have a single simple `omit` call with a list of disabled/readonly fields at the start of the suite.

Thought about what questions might come up about implementation. One might be about interaction with `skip`/`only`. I think `omit` should take precedence over those and otherwise should not be affected by them, so a separate layer of focus.

Are there any drawbacks to adding `omit`?

**Comment by ealush** [comment]
I think that what you're after is [optional with custom rules](https://vestjs.dev/docs/writing_your_suite/optional_fields#custom-omission-rules). Optional has two modes - one that only takes the field name. That's the default behavior, and one that takes a boolean/function value that describes whether the field should be omitted.

```js
optional({
  username: true // Will be omitted
});
```

The only difference between this and omitWhen is that optional runs on a second pass, meaning - it runs the field normally, but then excludes it. I can imagine it useful that if the optional condition is set from the get-go and not a function, it will behave the same as your imagined omit. That's especially true for async validations

**Comment by vonagam** [comment]
Oh, cool, I saw `optional` but it was documented mostly in the context of a value missing (event custom functions were kinda about that) and there was no example with booleans. Seem to be working, thanks.

**Comment by ealush** [comment]
Scratch My latest comment about the difference with what you're after. Just looked at the code, it behaves just as you'd expect. Wrote a few new tests to confirm that.

https://github.com/ealush/vest/commit/287f65e46490c7802a64261d5e2f5e0f4ac86946

**Comment by vonagam** [comment]
Hm... so why not introduce `omit` as an alias for `optional` of sorts?

To omit with `optional` I would need to reduce an array into an object and then vest will iterate over that object to make `SuiteOptionalFields.setOptionalField` (where third argument can be reused for all omitted, as they have no custom logic or need for checks). So it would be both more convenient and more performant to allow passing an array directly.

`omit(["asd"])` as `optional({"asd": true})`. (Just a thought, not a request.)

**Comment by ealush** [comment]
I am afraid it might be confusing with the behavior of `skip`, which works within the current scope, while optional works on the suite level. Essentially, at any nesting level where you put skip, it [only applies to the descendants of that scope](https://vestjs.dev/docs/writing_your_suite/including_and_excluding/skip_and_only#skipping-an-entire-group). A consumer of vest could mistake omit() to work just like this.

I am wondering if this is more reasonable to create a general-case omit() that would be similar to the way skip currently works.

**Comment by ealush** [comment]
I am afraid it might be confusing with the behavior of `skip`, which works within the current scope, while optional works on the suite level. Essentially, at any nesting level where you put skip, it only applies to the descendants of t
