### ISSUE TITLE
Performance issues on forms with lists of > 150 items

### ISSUE THREAD

**Issue by gdorsi** [ealush/vest#1145]
Hello!

Thanks for building this awesome library!

I love expressing the validation using a test-suite declaration style ❤️ 

I'm using it on a form with 3 lists of items, and when the total number of items start surpassing the 150 elements the computation time of every validation becomes > 100ms (measurement done on my laptop, a Mac M2 Pro)

This is a screenshot of the profiling of a keystroke on that form:
<img width="200" alt="Screenshot 2024-07-17 at 16 09 07" src="https://github.com/user-attachments/assets/d1e59677-aff8-482b-acae-46deb5f1c443">

Are there some best practices I can follow in order to avoid incurring into these kind of performance issues?

While I guess it's normal for performance to degrade as the number of fields to validate increases, it feels that the most of the cost comes from the nesting of the various helpers (each, omitWhen, skip, only etc...) so I'm kinda wondering if there are some optimization opportunities lurking inside these utilities.

To reproduce the issue I've create this repro: https://stackblitz.com/edit/vitejs-vite-gwp4ig

Given the simplicity of the example I needed to spawn more items in order to reproduce the same performance issues.

EDIT: More complex repro here --> https://stackblitz.com/edit/vitejs-vite-mlpchh

**Comment by ealush** [comment]
Thank you for this detailed issue and repro!

I think that’s going to be my weekend project this week. Let me have a deep
look into it, and hopefully I can come up with something smart.


I’ll try to see either whether the work can be reduced internally, or if we
can come up with some more interesting ideas of utilizing vest's building
blocks to achieve the same thing.

**Comment by gdorsi** [comment]
Thanks @ealush :heart:

Let me know if I can be of help

**Comment by ealush** [comment]
Hey @gdorsi I just went to check the repro blitz and it seems to only contain one field. Did you maybe create in in a fork?

**Comment by gdorsi** [comment]
> Hey @gdorsi I just went to check the repro blitz and it seems to only contain one field. Did you maybe create in in a fork?

Ah sorry, it was broken due to a typo on `querySelector`!

It is one input, but the validation runs on 500 fields.

<img width="720" alt="Screenshot 2024-07-18 at 23 23 28" src="https://github.com/user-attachments/assets/3347f68b-135a-4998-954e-7ee0cb6c16b8">

I can try to put toghether something more complex if you need a more realistic testing ground.

**Comment by gdorsi** [comment]
Here is a more complex test, with a mix of each and omitWhen. https://stackblitz.com/edit/vitejs-vite-mlpchh

Here I've managed to get similar performance values to what I'm experiencing in my app.

<img width="469" alt="Screenshot 2024-07-18 at 23 47 41" src="https://github.com/user-attachments/assets/082ac81c-20a6-4e52-93c3-fdea9afed291">

**Comment by ealush** [comment]
Thank you for the fixed repro @gdorsi !

I started mapping out the inefficiencies. Found three main inefficiencies so far, and I have taken care of the first one. Not done yet, and it is probably going to be the smaller cost saver of this changeset - but you can already start trying it out in this version: vest@5.4.0-dev-20240719-ed80

Can you let me know if that works any better for you?

**Comment by ealush** [comment]
Ok, so it took some fiddling, but I think I was able to come up with something that can somewhat improve the performance of large forms.

Here is the new version number you can install: `vest@5.4.0-dev-20240720-002e`
Right off the bat, it should shave off some significant time. It shaved off 40% in my test.
I can probably squeeze some more perf out of it, but I will need to find where the rest is coming from.
In the meantime, let me know if that works for you. If it does, I'll wrap it nicely and publish a production build.

Here's a the profile result of a simple form with 500 inputs with the production build
<img width="646" alt="image" src="https://github.com/user-attachments/assets/fe1db8f1-c155-4aca-a82c-23d2a8ed4864">

And here is the same app with my new development build
<img width="912" alt="image" src="https://github.com/user-attachments/assets/1bffaba2-ae8b-4dc5-b234-9154ed57b543">

**Comment by ealush** [comment]
Made some more progress on this issue, and now I am able to get results of anywhere between 35ms to 55ms for a 500 fields form.

This latest version can be tried using: `vest@5.4.0-dev-20240720-253c`
All the tests seem to pass, so I would consider this a major win.

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/ac2811e0-8897-4d2a-bc51-31c4686891af">

I think there are a few more performance gains we can make, especially around internal cache invalidation on each test run. Seems like we're invalidating the cache multiple times during the lifecycle of each tests while we shouldn't really. It is minor (.3ms), but over hundreds of tests it adds up:

<img width="819" alt="image" src="https://github.com/user-attachments/assets/378719c1-2243-4a6d-8102-2dc6785716aa">

**Comment by gdorsi** [comment]
That's awesome @ealush!

Tested `vest@5.4.0-dev-20240720-253c` on my app and got around 60% improvement!

|||
|--|--|
|Before|After|
|<img width="284" alt="Screenshot 2024-07-21 at 08 50 00" src="https://github.com/user-attachments/assets/a8b0197c-816d-4041-b179-355fa0667e07">|<img width="322" alt="Screenshot 2024-07-21 at 08 49 03" src="https://github.com/user-attachments/assets/e6c1b6b4-40fc-43f0-ae94-0f5dc28244dc">|

**Comment by ealush** [comment]
Ok, one last update @gdorsi 
I think I was able to get a another perf boost on this:

vest@5.4.0-dev-20240721-db6f

Should reduce response time by a few more ms. I was able to get down all the way from 127 to 35.

Lmk if you experience the same

**Comment by gdorsi** [comment]
In my case `vest@5.4.0-dev-20240721-db6f` has the same performance than the version before (`vest@5.4.0-dev-20240720-253c`)

<img width="341" alt="Screenshot 2024-07-21 at 15 41 48" src="https://github.com/user-attachments/assets/82666e73-0061-4123-b3ee-4dfcf8592346">

**Comment by ealush** [comment]
@gdorsi Thanks for all the feedback!

I created #1146 
Tomorrow I will check once again, and if everything looks good on my end, I will publish 5.4.0.

**Comment by ealush** [comment]
Looks like me committing the diff yesterday closed the issue. Sorry about this.

I just released 5.4.0. Can you please confirm this works as expected on your end?

**Comment by gdorsi** [comment]
Thanks a mill!

Can confirm that the `5.4.0` lands a huge improvement on performance, our test suite pass and  and I've not observed any regression so far.

Tested on the same form but with a different number of fields.

Test on form with 60 fields:
|||
|--|--|
|Before|After|
|<img width="318" alt="Screenshot 2024-07-22 at 14 14 45" src="https://github.com/user-attachments/assets/d5712c4f-74be-4061-a12d-1686f4b63e36">|<img width="279" alt="Screenshot 2024-07-22 at 14 16 18" src="https://github.com/user-attachments/assets/e521e162-b5db-40da-87df-931c78d05d51">|

Test on form with 180 fields:
|||
|--|--|
|Before|After|
|<img width="318" alt="Screenshot 2024-07-22 at 14 19 55" src="https://github.com/user-attachments/assets/f0e96c79-e43c-4fb4-9a41-2840a92f27ba">|<img width="204" alt="Screenshot 2024-07-22 at 14 17 28" src="https://github.com/user-attachments/assets/54d02d96-0560-45df-af19-41e2e969142e">|

For now this is a great result as I don't think that there are too many forms of > 100 fields in the wild and the performance with < 100 fields now is above the 60FPS.

Still wondering why the performance degradation isn't linear on the form size.
Will dig more into it on my free time to see if I can find some other performance opportunities.

**Comment by ealush** [comment]
I've got a pretty good idea why this is not linear with the amount of fields.
The reason is that for each of the fields, there are some operations that traverse the entire tree, so treeSize*treeSize.

I'm looking for a way to reduce the needs of these as well, because we might not always need this kind of traversal, but at least for now - we were able to get some significant improvement.
The rest will require some rearchitecting of the test function, which I am looking into.

For now, I am closing this issue. Thanks for helping me with the fast feedback loop!

**Comment by gdorsi** [comment]
Ah good!

Thanks for the very quick fix!

**Comment by paulodiogo** [comment]
I'm facing the same issue. I have a dynamic form that works well with around 100 fields, but when I try a larger form, the performance gets worse. For example, when I validate a part of the form the time starts at 1ms, but by the end of the form, the same validation takes 600ms+.

My form:
1. PARENT
    1. Children ((using [each](https://vestjs.dev/docs/writing_tests/advanced_test_features/dynamic_tests))From 1ms to 600ms+) (suite 1)(for each child call suite 2)
       1. Children  (suite 2 calls suite 3)
          1. Children  (suite 3 calls suite 4)  

I created these suites for each part of the form when I'm dealing with them individually. But I need to validate the whole form.

**Comment by ealush** [comment]
Hey, thanks for this update.

As: did you try by any chance 5.4.0 that got published today? Did it make
it any better?

Also, do you have a repro that I can play with? With the latest version I
got 150ms for a 1500 field form, so I would love to see where the
difference may be and where I can improve the validation performance
(either within vest or in your use case specifically).

**Comment by paulodiogo** [comment]
I'm facing the same issue. I have a dynamic form that works well with around 100 fields (planning to go 10000+), but when I try a larger form, the performance gets worse. I created theses suites for each part of the form when I'm dealing with them individualy.

https://stackblitz.com/edit/vitejs-vite-sresjq?file=tests%2Ffields.validation.test.js

Created two test files:

fields.validation.not.nested.test.js
NN time1: 2.635ms
NN time10: 2.285ms
NN time100: 15.97ms
NN time500: 120.41ms

fields.validation.test.js (nesting the suite)
NESTED time1: 2.435ms
NESTED time10: 4.175ms
NESTED time100: 222.195ms
NESTED time500: 15.656s

Note that fields.validation.js I use a inner.fields.validation.js suite.

**Comment by ealush** [comment]
H

**Comment by ealush** [comment]
Hey @paulodiogo, thanks for reporting this and creating this detailed test case scenario.
I do indeed see the issue, and I believe it is related to what I replied above to @gdorsi about the increase not being linear.

One thing I think you can do, and still achieve everything you need is to nest via functions rather than suites.

Currently your suite looks like this:

```
const suite1 = create(() => {/*...*/})

const suite2 = create((data) => {
  suite1(data)
})
```

If you just replace it with:

```
function nestedTests1(data) {
  test(/*...*/);
}

const suite = create((data) => {
  nestedTests1(data)
})
```

You should see an immediate perf boost, without losing any capability. I do want to improve the performance of nested suites (as I mentioned above), but that would require making some changes to the way the test function works, and will require more time.

Will such a solution work for you in the meantime?

**Comment by paulodiogo** [comment]
**Yeah! This change improved the time! Thank you!**

From 23secs to 300ms @ealush

**Comment by ealush** [comment]
@paulodiogo, @gdorsi 
I made yet another improvement to Vest's infra that should further reduce the initialization time of large suites. Can you try Vest@5.4.1 and let me know how that works?

This should do the trick: https://github.com/ealush/vest/commit/0462bc0d22449029e0522648db126776c3dba2aa

**Comment by gdorsi** [comment]
> @paulodiogo, @gdorsi 
> I made yet another improvement to Vest's infra that should further reduce the initialization time of large suites. Can you try Vest@5.4.1 and let me know how that works?
> 
> This should do the trick: https://github.com/ealush/vest/commit/0462bc0d22449029e0522648db126776c3dba2aa

Awesome!

I'm on vacation now and won't be able to give you a feedback before next Monday.

**Comment by ealush** [comment]
No problem, enjoy your time off!

**Comment by gdorsi** [comment]
@ealush 

v.5.4.1 brings another huge performance improvement in our form 🎉 


|||
|--|--|
|v5.4.0|v5.4.1|
|<img width="297" alt="Screenshot 2024-08-14 at 10 09 00" src="https://github.com/user-attachments/assets/a9ad768e-f80f-4fe3-8fe3-fd2bfb0b7794">|<img width="385" alt="Screenshot 2024-08-14 at 10 11 30" src="https://github.com/user-attachments/assets/594d627e-2047-4b62-b5dc-de6d91436089">|

Test done editing a single field on a big form of 100 fields

Thanks!

**Comment by ealush** [comment]
Yes! Glad to hear that this worked for you. Closing the issue now as we extracted every last drop of it.

Thanks for testing reporting back each time.

**Comment by ealush** [comment]
Also, this is now on twitter https://x.com/evyataral/status/1823776130379272684
