### ISSUE TITLE
React example 2 -  password has wrong validation

### ISSUE THREAD

**Issue by mosheKerbel** [ealush/vest#206]
Steps to reproduce:
1. Type in a password with more than 1 char.
2. Focus out of the field

Expected:
Field should pass validation
Actual:
Field fails on validation

I did not check yet wether the issue is due to the example code or the actual library.

**Comment by ealush** [comment]
Hey, @mosheKerbel, thanks for checking out the library.
I am assuming you're talking about this example: https://stackblitz.com/edit/vest-react-registration?file=validate.js

I tested it now, it seems to be working as expected.

The password validation rules are:
1. *Must* have at least one **digit**.
2. *Should* be 7 chars or longer.

```js
  test('password', 'Must have at least one digit', () => {
    enforce(data.password)
      .matches(/[0-9]/);
  });

  test('password', 'Strength: Weak', () => {
    vest.warn();
    enforce(data.password)
      .longerThan(6);
  });
```

![image](https://user-images.githubusercontent.com/11255103/85211526-dc200e80-b352-11ea-982c-23bfae98cf8b.png)

![image](https://user-images.githubusercontent.com/11255103/85211536-eb06c100-b352-11ea-9afb-e15d0a2d6596.png)

![image](https://user-images.githubusercontent.com/11255103/85211574-302af300-b353-11ea-9a47-d8e2df2ab0db.png)

**Comment by mosheKerbel** [comment]
Hey @ealush 
When I created the issue I did it from my phone and i was not able to attach the screenshot.
Here is what I'm getting from the link you put here - https://stackblitz.com/edit/vest-react-registration?file=validate.js
![image](https://user-images.githubusercontent.com/7388217/85218343-182e9000-b3a2-11ea-8b6a-da17854fa785.png)

**Comment by ealush** [comment]
Hey, please note that in this demo the password has to have at least one digit (0-9), not just any character. Try typing a number and you'll see that the validation passes as expected.

**Comment by mosheKerbel** [comment]
Ohh right
My bad, apologies 🙈 
In anyways, love the library and the idea behind it, would definitely try it in the next project I need to use validations.

**Comment by rtkac** [comment]
Just instead of
`enforce(data.password).isNotBlank();`
do this
`enforce(data.password).isNotEmpty();`
