### ISSUE TITLE
Add Vuejs example

### ISSUE THREAD

**Issue by ealush** [ealush/vest#248]
Improve the documentation by adding a Vuejs sandbox.

**Comment by eyalcohen4** [comment]
[Made a sample](https://codesandbox.io/s/vest-vue-example-v9rpo?file=/src/App.vue)

I'm not a Vue expert, so maybe we can get feedback from more experienced devs before posting.

**Comment by MaxMonteil** [comment]
I really love this library and would like to help flesh out the Vue use cases.

I changed @eyalcohen4 sample to use more idiomatic Vue, let me know what you think.

[Sample](https://codesandbox.io/s/vest-vue-example-uv6u0?file=/src/App.vue)

**Comment by eyalcohen4** [comment]
LGTM
Thanks, Max. I'll update the sandbox
