### ISSUE TITLE
[N4S] Add jest style enforce rule failures

### ISSUE THREAD

**Issue by ealush** [ealush/vest#285]
At the moment, validation rules are simple functions that return a boolean. If the rule's return value is false, enforce will throw an Error.

Rule example:
https://github.com/ealush/vest/blob/69eacb388ad9fac8e403351df5ab5347d6298edf/packages/n4s/src/rules/greaterThan/index.js#L3-L5

And where it throws:
https://github.com/ealush/vest/blob/69eacb388ad9fac8e403351df5ab5347d6298edf/packages/n4s/src/enforce/runner/index.js#L14-L16

This means that the thrown error is always a generic one, not indicating the rule thrown, or the expected behavior of the rule.

Jest has a nicer interface for constructing matchers that also includes a custom failure message for that rule:
https://jestjs.io/docs/en/expect#expectextendmatchers

This can be very beneficial for Vest DEV_MODE that's being planned. A debug dump could log all the failed rules and their failure messages.

I would like to preserve the current behavior of Vest rules to prevent a breaking change, but also support the more verbose failure style of:
```js
{
	message: (ruleName, enforceValue, ...args) => ``, // someErrorMessage
    pass: true/false
}
```

**Comment by vligas** [comment]
Hi, i reviewed the jest code and I will be adding a `validateResultShape` and a `transformResultShape` functions so in first place we could parse all supported formats to a final one with defaults values.

```js
transformResultShape(true) // { pass: true, message: '[Enforce] Generic message'}
transformResultShape({ pass: true, message: 'Custom Message'}) // { pass: true, message: '[Enforce] Custom Message'}
transformResultShape({ pass: true }) // { pass: true, message: '[Enforce] Generic message' }
```

that way to deprecate/add a valid rule result, you only need to change those two functions and the rest of the lib could be only aware of the verbose one.

In the other hand what should `transformResultShape` in case that the rule returned an invalid format? pass silently? or maybe return a failing test like `{ pass: false, message: '[Enforce] Wrong rule result format' }`

what do you think @ealush?
