### ISSUE TITLE
TypeScript definition not getting published to npm

### ISSUE THREAD

**Issue by narkeeso** [ealush/vest#295]
At first I didn't think vest had a TypeScript declaration file but double checked the repo and found the types. I dug into `node_modules/vest` and the declaration file seems to be missing.

![image](https://user-images.githubusercontent.com/17995/89240349-b4a69d80-d5b0-11ea-9a4a-8d8bd0d9ea93.png)

**Comment by ealush** [comment]
Hey @narkeeso - thanks for opening this issue.

This is actually correct. The published version on npm is the `stable` version (correlates with the [stable branch](https://github.com/ealush/vest/tree/stable)). The next release, 2.1 is the one you see in the latest branch - and that's where the type declarations do exist.

I will soon release version 2.1 (When I am comfortable with its added feature set and stability), and with it the type declarations will be published.

I hope this answers it.

**Comment by narkeeso** [comment]
Looking forward to it @ealush! I am loving validating with vest!
