### ISSUE TITLE
Export validator rules individually

### ISSUE THREAD

**Issue by ealush** [ealush/vest#311]
Currently `enforceExtended` is 29kb due to the validator.js rules. If we export each rule individually and let consumers mix and match it will make it way smaller.

```js
import { enforce } from 'vest';
import isEmail from 'vest/enforce/isEmail;

enforce.extend({ isEmail })
```

**Comment by vligas** [comment]
Ok, are you looking for left some of those rules like defaults?

I took a look into the code of enforce I think that this could be accomplish by just changing this 
```js
// const rulesObject = { ...rules };
const rulesObject = { };
```
https://github.com/ealush/vest/blob/latest/packages/n4s/src/enforce/index.js

and change the imports for exports here https://github.com/ealush/vest/blob/latest/packages/n4s/src/rules/index.js, but I'm not quite sure of how to make the export from `vest/enforce/ruleName` without changing the folder structure

**Comment by Moses3301** [comment]
I would like to take this issue, 
but first I want to be sure that I fully understand it.
the vest\packages\n4s\src\extended\rules\index.js file import the rules and export it all like that:
`
import isEmail from 'validator/es/lib/isEmail';
export default {
  isEmail,
  ...
};`
and the rules need to exported individually like that:
`
import isEmail from 'validator/es/lib/isEmail';
...;
export default isEmail;
...;
`
Is that right?
thanks in advance.

**Comment by ealush** [comment]
Hey @Moses3301, thanks for reaching out!

Yes, you understand it correctly. The idea in general is to mirror the validator.js rules for easier consumption (no need to install multiple packages), but still have it as their own exports so that it doesn't add much unneeded bloat to whoever's using it.

One thing I am thinking, is that we don't need to have that supported on the n4s packages, but just on vest (n4s isn't really used outside of vest).

Setting this up would probably require adding some rollup configuration to support these exports. There is a need to add a similar setup to the utilities config, only to support the exported enforce rules.

See here:
https://github.com/ealush/vest/blob/latest/packages/vest/config/rollup/rollup.config.js

It should be relatively straightforward, but if you require any assistance, I am here :)
