### ISSUE TITLE
Restructure state directory

### ISSUE THREAD

**Issue by ealush** [ealush/vest#312]
The idea is to move all the modules that directly relate to a suite and put them in the same directory: `packages/vest/src/core/suite`.

- [ ] create core/suite directory
  - [ ] move createSuite to suite/create
  - [ ] move validate to suite/validate
  - [ ] move registerSuite to suite/register
  - [ ] move reset to suite/reset
  - [ ] move remove to suite/remove
  - [ ] move getSuiteState to suite/getState
  - [ ] move patch to suite/patch
  - [ ] move cleanupCompletedSuite to suite/cleanupCompleted
  - [ ] move getSuite to suite/getSuite (maybe just get? need to see how it feels to actually use it)
  - [ ] move setSuite to suite/setSuite (maybe just set? need to see how it feels to actually use it)
  - [ ] Move hasRemainingTests to suite/hasRemainingTests

**Comment by reidysj** [comment]
Can I take this on? I'm new to contributing and organizing dirs is my favorite 😁

**Comment by ealush** [comment]
Hey @reidysj, definitely. I'd love that. 

It is not a very challenging task, but it might get a little tedious - feel free to break it down and start small by moving just a part of these folders.

Also, I am still trying to find the best structure myself, so if you're thinking of a better structure while at it I'm happy to hear.

Thank you 🙏🏻

**Comment by NorbertLuszkiewicz** [comment]
Hey, can I help to fix this issue ?
