### ISSUE TITLE
FEAT: add `get` and `reset` interfaces to suite directly

### ISSUE THREAD

**Issue by ealush** [ealush/vest#315]
At the moment you can use `vest.get(suiteName)` to get the suite's state, and `vest.reset(suiteName)` to erase it.

It could be nice to be able to access those without having to hold a reference to the suite name:

```js
// validate.js

import vest from 'vest';

export default vest.create('suite-name', () => {
 /* ... */
});
```

```js
// app.js

import v from './validate.js';

const res = v.get();

v.reset();
```

Can probably be added here: 
https://github.com/ealush/vest/blob/latest/packages/vest/src/core/createSuite/index.js#L44-L58

**Comment by vligas** [comment]
Can I help with this?

**Comment by ealush** [comment]
Hey @vligas, yes, of course!

As mentioned, the main file you should probably add the functions to is `createSuite/index`. The tests should reside next to it as well.

Let me know if you need any help getting things to work.
