### ISSUE TITLE
Add test.each for iterative tests over an array

### ISSUE THREAD

**Issue by ealush** [ealush/vest#393]
Implement test.each (described here: https://github.com/ealush/vest/issues/356#issuecomment-684780967).

Similar to [jest's each function](https://jestjs.io/docs/en/api#testeachtablename-fn-timeout), but slightly different. It can be discussed if we should support the `printf` formatting, or find an alternative.

**Comment by ealush** [comment]
```js
test.each(table)('Name', 'MSG', (...args) => {})
```

**Comment by ealush** [comment]
```js
z`Some message (${(arg1) => arg1})`
```

**Comment by omriLugasi** [comment]
@ealush 
Currently there are 3 options for string interpolation (error message).
1.
```js
 test.each([[1,2,3]])('fieldName', '{{ a }} is greater then 5', (a, b, c) => {
    enforce(a).greaterThan(5)
})
// Will print 1 is greater then 5
```
2. With string format (like https://jestjs.io/docs/en/api#testeachtablename-fn-timeout)
3. ```  z`Some message (${(arg1) => arg1})` ``` Actually I cant understand how you want to implement [your](https://github.com/ealush/vest/issues/393#issuecomment-696283653) suggestion?

**Comment by omriLugasi** [comment]
Another options is to let the user choose to put static error message as string or to pass function that return the error message.

For example: 

With Static error message
```js
test.each([[1,2,3]])('fieldName', 'This is a static error message', (a, b, c) => {
    enforce(a).greaterThan(5)
})

```

With generic error message

```js

const generateErrorMessage = (a, b, c) => `${a} is greater then 5`

test.each([[1,2,3]])('fieldName', generateErrorMessage, (a, b, c) => {
    enforce(a).greaterThan(5)
})

```
@ealush let me know what you think of this approach :)

**Comment by ealush** [comment]
Hey @omriLugasi, sorry, I missed your message.

Yes, this is very much possible - and technically, it is the same as using a tagged function:
![image](https://user-images.githubusercontent.com/11255103/94586200-9fd14800-0289-11eb-8e51-2a35297007f1.png)

The reason I am reluctant to just let the consumer specify a function is that it prevents us from actually knowing whether it is their test call, or their string generation function.

Why? Because message is optional, so when the consumer does this:
```js
test.each([1,2,3])('fieldName', someFn);
```
We have no real way of knowing whether the consumer intended for the second argument to be the test call, or the string generation function.  Using our own tagged function allows us to know which function is really called.

.

But thinking about what you said, we can pretty safely assume that the last argument is always the test function, and if it is not, then it is a user error, and we should throw an exception here.
