### ISSUE TITLE
[N4S] Rule isNegative | isPositive

### ISSUE THREAD

**Issue by ealush** [ealush/vest#401]
Add a new enforce rule:

```js
enforce(-5).isNegative() // ✅
enforce(5).isNegative() // 🚨
```

```js
enforce(5).isPositive() // ✅
enforce(-5).isPositive() // 🚨
```

**Comment by sagivStekolshik** [comment]
what should happen when:

```javascript
enforce(0).isNegative() // ❓
 ```
or

```javascript
enforce(0).isPositive() // ❓
```

**Comment by ealush** [comment]
Hey @sagivStekolshik, that's an excellent question.
The truth is that whether zero is positive or negative is context dependent, and sometimes it is regarded as neither. 

This means that we can arbitrarily decide how we want to treat it.

For example, we could decide that in both cases it is `false`
```js
enforce(0).isNegative() // false
enforce(0).isPositive() // false
```
or even treat it always as `true`
```js
enforce(0).isNegative() // true
enforce(0).isPositive() // true
```

In our case, I think it would be most intuitive to start with the negative case:
> negative is everything that's smaller than zero `value < 0`

So anything else would be considered as positive.
In that scenario `0` would be treated as positive.

The one exception is - how to deal with signed zero `-0`, because:
```js
-0 === 0 // true
Object.is(-0, 0) // false
```

But since signed zero is so rare in js, it might not even be worth looking at.

**Comment by sagivStekolshik** [comment]
My idea was using `Math.sign()` to get the number or string(works as well)
sign function returns 0 or -0  according to [MDN]( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sign)
so going the `0 -> false` route will be easier 
going the `0 isPositive number` will be even easier as it can be the "negative" of `isNegative`

**Comment by ganeshpatil0101** [comment]
Hi @ealush 
I would like to work on this issue.
Please assign to me. I already started working on it and is there any diagram or documentation to get started?
Thanks,

**Comment by zivkaziv** [comment]
Is this issue still open?

**Comment by ealush** [comment]
@ganeshpatil0101 
> Hi @ealush
> I would like to work on this issue.
> Please assign to me. I already started working on it and is there any diagram or documentation to get started?
> Thanks,


@zivkaziv 
> Is this issue still open?

Yes. No need to assign anyone, simply submit a pr and we'll get it merged 🙂

**Comment by ganeshpatil0101** [comment]
@zivkaziv @ealush  I can see other unit tests are failing. does that expected ? I will add unit test for isNegative & isPositive and then raise pr.

**Comment by ganeshpatil0101** [comment]
@ealush @zivkaziv  unit tests are working fine. But on my local example of vest with vanilla is not working. I will check it. Thanks.

**Comment by ealush** [comment]
@ganeshpatil0101 do you have a branch you can share with those changes that do not work? I might be able to help.

**Comment by ganeshpatil0101** [comment]
@ealush Please review and merge the PR https://github.com/ealush/vest/pull/433
New unit tests are added & all tests are passed.
I request you to test this feature with one real example as I am having issues to setup a vest - vanilla example on local. 
Please let me know you if there any changes required.
Thanks.
