### ISSUE TITLE
Cross Field Validations

### ISSUE THREAD

**Issue by daniel-sc** [ealush/vest#475]
Are cross field validations possible? Eg "either email or phone must be set".

**Comment by ealush** [comment]
Hey @daniel-sc, thanks for reaching out. Yes, cross field validation is possible and quite simple. There are multiple ways of achieving this, depending on your specific validation strategy.

I am adding a few example. I recommend you open the live demos as they add a few more details.

## Option 1: use the `any` utility

Your specific example can be handled with the `any` utility function. The `any` utility function takes a series of functions or expressions, and as long as at least one evaluates to `true`, it will mark your validation as passing.

There are two possible ways to use `any`:

### Use any to run one of multiple tests

the `any` utility will run each function until a passing test is found. This means that once one of the tests passes, the others won't run at all, saving you some performance.

Live Demo: https://codesandbox.io/s/demo-forked-tdj92?file=/src/validate.js

```js
import vest, { test, enforce } from "vest";
import any from "vest/any";

export default vest.create("form_name", (data = {}) => {
  any(
    () =>
      test("email", "Email or phone must be set", () => {
        enforce(data.email).isNotEmpty();
      }),
    () =>
      test("phone", "Email or phone must be set", () => {
        enforce(data.phone).isNotEmpty();
      })
  );
});
```

### Use any to run use different conditions in the same test

You could also use any within your test, if you have a joined test for both scenarios. This means that you have to return a boolean from your tests.

Demo: https://codesandbox.io/s/demo-forked-ltn8l?file=/src/validate.js

```js
import vest, { test, enforce } from "vest";
import any from "vest/any";

export default vest.create("form_name", (data = {}) => {
  test("email_or_phone", "Email or phone must be set", () =>
    any(
      () => {
        enforce(data.email).isNotEmpty();
        return true;
      },
      () => {
        enforce(data.phone).isNotEmpty();
        return true;
      }
    )
  );
});
```


## Option 2: use if/else

If your field depends on a different field's existence or a different simple condition, you could use a basic if/else statement.
In the following example I only validate `confirm` if password is not empty:

DEMO: https://codesandbox.io/s/demo-forked-z2ur9?file=/src/validate.js

```js
import vest, { test, enforce } from "vest";

export default vest.create("user_form", (data = {}) => {
  test("password", "Password is required", () => {
    enforce(data.password).isNotEmpty();
  });

  if (data.password) {
    test("confirm", "Passwords do not match", () => {
      enforce(data.confirm).equals(data.password);
    });
  }
});
```

## Option 2.5 if/else based on a different field
Sometimes you might want to run a certain validation based on the validation result of a previously run test, for example - only test for password strength if password DOESN'T have Errors. You could access the intermediate validation result and use it mid-run.

This requires using the function created from vest.create():

```js
import vest, { test, enforce } from "vest";

const v = vest.create("user_form", (data = {}) => {
  test("password", "Password is required", () => {
    enforce(data.password).isNotEmpty();
  });

  if (!v.hasErrors('password')) {
    test("password", "Password is weak", () => {
      enforce(data.password).longerThan(8);
    });
  }
});
export default v;
```

**Comment by daniel-sc** [comment]
@ealush thanks for the info!
Like it!

**Comment by ealush** [comment]
Should probably add this as a docs section. Thanks for the good question!

**Comment by daniel-sc** [comment]
@ealush The live demo seems to be wrong:
![image](https://user-images.githubusercontent.com/117919/97814838-66c23400-1c8a-11eb-9cab-f7566c64ede8.jpeg)

**Comment by ealush** [comment]
@daniel-sc, you are right. I tested `email` twice but never `phone`, so the example "worked" correctly, but I had a bug 😅
Updated the link, and here it is again: https://codesandbox.io/s/demo-forked-ltn8l?file=/src/validate.js

**Comment by ealush** [comment]
Also, added another example (2.5). Could be very useful.
