### ISSUE TITLE
add enforce.oneOf compound for mutually exclusive validations

### ISSUE THREAD

**Issue by ealush** [ealush/vest#513]
Similar to [anyOf](https://github.com/ealush/vest/blob/latest/packages/n4s/src/enforce/compounds/anyOf.js), we need a mutual exclusion rule: `oneOf`.

In the following example `value` must either be shorter than five OR longer than 10, but never both.
```js
enforce(value).oneOf(
  enforce.longerThan(10),
  enforce.shorterThan(5),
);
```

This can be even more useful when combined with templates and shape validations:

```js
const User = enforce.template(
  enforce.shape({
    id: enforce.isNumber(),
    name: enforce.shape({
      first: enforce.isString(),
      last: enforce.isString(),
      middle: enforce.optional(enforce.isString()),
    }),
  })
);
const Group = enforce.template(
  enforce.shape({
    id: enforce.isNumber(),
    name: enforce.isString(),
  })
);

enforce(value).oneOf(
  User,
  Group
);
```

**Comment by ahsanbagwan** [comment]
I would like to give this a try. What else do I take a look for help except this [file](https://github.com/ealush/vest/blob/latest/packages/n4s/src/enforce/compounds/anyOf.js)

**Comment by ealush** [comment]
Hey @ahsanbagwan, that would be awesome! Thank you 🙏🏻

So here's the general guideline:

1. Create a new file called `oneOf` right next to anyOf. It should be pretty much the same, implementing the rules.some logic with some other counter mechanism.

2. To actually have it used by enforce, add it to this [compounds export](https://github.com/ealush/vest/blob/latest/packages/n4s/src/enforce/compounds/compounds.js#L6)

3. Add a new test file [here](https://github.com/ealush/vest/tree/latest/packages/n4s/src/enforce/compounds/__tests__) and test different scenarios

4. Add suitable types [here](https://github.com/ealush/vest/blob/latest/packages/vest/src/typings/enforce.d.ts#L90) and [here](https://github.com/ealush/vest/blob/latest/packages/vest/src/typings/enforce.d.ts#L196) (basically duplicate anyOf).

5. If you feel like it, also add suitable docs for this feature [here](https://github.com/ealush/vest/blob/latest/packages/n4s/docs/compound.md)

**Comment by hpsharon** [comment]
Same here 👋

**Comment by ealush** [comment]
If either of you is interested, there's a near identical issue https://github.com/ealush/vest/issues/521
