### ISSUE TITLE
enforce.extend wrong typings

### ISSUE THREAD

**Issue by Feshchenko** [ealush/vest#559]
Hi. ✋🏿 
I'm trying to create custom rule with return value, according to https://ealush.com/vest/#/./n4s/custom?id=custom-rules-return-value
But I got typescript error 😭 
<img width="1420" alt="Screenshot 2021-01-19 at 20 03 54" src="https://user-images.githubusercontent.com/7198398/105076621-f3afa900-5a93-11eb-999f-9a32fd634d30.png">
I think that problem is here:
https://github.com/ealush/vest/blob/latest/packages/vest/src/typings/enforce.d.ts#L129
Returned value should be like:
```
boolean | { pass: boolean, message: () => string }
```

**Comment by ealush** [comment]
Thank you for reporting @Feshchenko.
You are right. The type was missing. I pushed a fix for this in 3.0.2.

Can you please confirm that it works as expected now?

**Comment by Feshchenko** [comment]
Hello, @ealush.
Typings are correct now.
I have another problem with enforce.extend.
I created small `codesandbox` example to show you my problem: https://codesandbox.io/s/vest-extend-re27v?file=/src/index.js
I thought that test suite should return message from resulting object which is ''Message from enforce.extend" (line: 7), but I've got `undefined` instead 😭 . 
Did I get documentation wrong?

**Comment by ealush** [comment]
@Feshchenko Thank you for this message.

Initially the extended message was added for easier debugging in development, but the way you tried to use it actually makes a lot of sense to me. That's a super useful feature that can be beneficial for many users.

So I went ahead and added it.

I released a new development version: `vest@3.1.0-dev-22d3d0` with this functionality.
You can check it out in this sandbox:
https://codesandbox.io/s/immutable-tree-ruqbc?file=/src/index.ts

Briefly on how to use this new functionality:
If you wish to use the value from your custom enforce message, you should omit the message from your test, so vest can tell you want to use the thrown string. A full usage example in the sandbox.

If it works for you, I will release it as a minor release later today. Please let me know if it works for you.


Here is the change itself: https://github.com/ealush/vest/pull/560

**Comment by Feshchenko** [comment]
I use `vest@3.1.0-dev-22d3d0` - for my sandbox, it works great.
@ealush thank you for quick response and fixes :)
I'm waiting for new version to use this awesome feature :)

**Comment by ealush** [comment]
@Feshchenko Included in https://github.com/ealush/vest/releases/tag/3.1.0
