### ISSUE TITLE
validate + promisify wrong typings

### ISSUE THREAD

**Issue by jorisre** [ealush/vest#562]
Hi 👋🏻 

I'm adding sync/async validation mode to [react-hook-form's vest resolver](https://github.com/react-hook-form/resolvers) and at the same time, I'm updating from V2 to V3, thanks for your great work 👏🏻 

I tried to use `promisify` but I get TypeScript errors.
You can find here a reproduction: https://codesandbox.io/s/pedantic-pond-15zuc

**Comment by ealush** [comment]
Hey @jorisre, thank you for reporting this 🙏🏻

Looks like there were two issues:
1. The documentation had an error - that section that suggested passing an invoked suite to promisify (your validate2 example). Fixed. https://ealush.com/vest/#/./utilities?id=promisify.

2. The ts typings were indeed incorrect. I fixed it in `vest@3.1.1`. 
Here's the working example: https://codesandbox.io/s/infallible-glitter-0p1lb?file=/src/index.ts

Please let me know if that works for you.

**Comment by jorisre** [comment]
Hey @ealush 👋🏻

Thanks for the quick reply ! Seems good in your example and on my side too 🙂

Issue solved ✅
