### ISSUE TITLE
vest/schema problems with typescript

### ISSUE THREAD

**Issue by therealpaulgg** [ealush/vest#564]
Hi,

I was trying to write some code to test the experimental vest/schema updates we discussed a couple of weeks ago (finally got to it at work). Not sure why but my Typescript project refuses to use vest/schema because it simply says it is an interface type. The error I get is:

`'schema' only refers to a type, but is being used as a value here.`

I cannot get typescript to import the file in vest/schema.js for the life of me. Any ideas?

**Comment by ealush** [comment]
Hey @therealpaulgg, thanks for reporting that.

You are right. Sorry that you experienced it. I just released `3.1.2` with type fixes for vest/schema. You can see it working here: https://codesandbox.io/s/heuristic-leaf-kf6s6?file=/src/index.ts

Let me know if there's anything else I can help with

**Comment by ealush** [comment]
@therealpaulgg, may I close this issue?

**Comment by therealpaulgg** [comment]
Yes, it is working as expected.

I've been busy with a ton of stuff at work - I'll definitely provide feedback once I get to writing my validation system using Vest.
