### ISSUE TITLE
pref: add cache around collectFailureMessage

### ISSUE THREAD

**Issue by ealush** [ealush/vest#576]
In each call to collectFailureMessage (https://github.com/ealush/vest/blob/latest/packages/vest/src/core/produce/collectFailureMessages.js#L14-L36) we go and recalculate all the values. This can be prevented if we cache it by the `testObjects` array.

Cache module is here: https://github.com/ealush/vest/blob/latest/packages/vest/src/lib/cache.js

**Comment by cth0604** [comment]
Hi, I would like to tackle this issue if it's possible. Could you please let me know if the issue is still available? Thanks!

**Comment by rreckonerr** [comment]
@cth0604 I'm pretty sure you can start working on the task straight away without even asking for permission.

**Comment by ealush** [comment]
Hey @cth0604, sorry for replying late. Sure, go ahead - if you need any assistance let me know :)

**Comment by HttTavares** [comment]
> Hi, I would like to tackle this issue if it's possible. Could you please let me know if the issue is still available? Thanks!

Would you be interested in some help?

**Comment by CodeWithBlaze** [comment]
Hey , I am new to open source and want to try this issue is it available ?

**Comment by ealush** [comment]
Irrelevant due to v4 coming out soon.
