### ISSUE TITLE
Add suite method shorthands

### ISSUE THREAD

**Issue by ealush** [ealush/vest#577]
At the moment we can access all suite methods via suite.get(). Alternatively, it would be very simple to add all the suite methods directly on top of suite:

Functions should be added here: https://github.com/ealush/vest/blob/latest/packages/vest/src/core/suite/createSuite.js#L60
They can all rely internally on `suite.get()`.

Types should be added here: https://github.com/ealush/vest/blob/latest/packages/vest/src/typings/vest.d.ts#L168

Type summary:
```ts
hasErrors: (fieldName?: string) => boolean;

hasWarnings: (fieldName?: string) => boolean;

getErrors(): { [fieldName: string]: string[] };
getErrors(fieldName: string): string[];

getWarnings(): { [fieldName: string]: string[] };
getWarnings(fieldName: string): string[];

hasErrorsByGroup(groupName: string): boolean;
hasErrorsByGroup(groupName: string, fieldName: string): boolean;

hasWarningsByGroup(groupName: string): boolean;
hasWarningsByGroup(groupName: string, fieldName: string): boolean;

getErrorsByGroup(groupName: string): { [fieldName: string]: string[] };
getErrorsByGroup(groupName: string, fieldName: string): string[];

getWarningsByGroup(groupName: string): { [fieldName: string]: string[] };
getWarningsByGroup(groupName: string, fieldName: string): string[];
```

**Comment by ruksina25** [comment]
☑️

**Comment by UdattaChowdhury** [comment]
Hello, maintainer. I am new to open source. Would like to work on this issue. Can you please guide me?

**Comment by Man-RP** [comment]
hey,
I would like to know where can I write a unit test for this implementation

**Comment by ealush** [comment]
Irrelevant due to v4 coming out soon
