### ISSUE TITLE
No contributing guidelines available

### ISSUE THREAD

**Issue by lirantal** [ealush/vest#6]
The PR template references a CONTRIBUTING.md file for contribution guidelines but the file is unavailable in the repository.

PR template text:

```
<!--
Before creating a pull request, please read our contributing guidelines:

CONTRIBUTING.md

Remember: Unless it is an urgent bugfix, please use `next` as the base for your PR

Please fill the following form (leave what's relevant)
-->
```

**Comment by ealush** [comment]
Very good point. Will be taken care of. Thank you :)

**Comment by ealush** [comment]
Done in https://github.com/ealush/vest/pull/8. Thanks again :)
