### ISSUE TITLE
.isEmpty() doesn't check for whitespaces

### ISSUE THREAD

**Issue by sergiocasao** [ealush/vest#676]
`isNotEmpty` returns no errors when `data.username` is just whitespaces.

```
const suite = vest.create('NewUserForm', (data) => {

  test("username", "Username is required", () => {
    enforce(data.username).isNotEmpty();
  });

});

```

**Comment by ealush** [comment]
Sorry @sergiocasao for replying late. Yes, this indeed seems like a feature that could be useful, but not as part of "isEmpty" as it would be a breaking change. Instead, @Pizzo15 added today the `isBlank` rule, which is available from `Vest@3.2.6`.

Again, sorry for taking a while - but this seems to be solving the issue.

Thanks for reporting this!
