### ISSUE TITLE
No email validation

### ISSUE THREAD

**Issue by martygo** [ealush/vest#712]
A regex could be created to take care of email validation in the most common scenarios.

By the way, how can I contribute to the project, in addition to reporting issues?

Thanks.

**Comment by ealush** [comment]
Hey @martygo! Thank you for reaching out.

Vest intentionally does not include some built in validations, email is one of them.

Even though these all have strict specs, I learned the hard way that they are more of business decisions that technical matters. What is a valid email? Well, there's a clear spec - but not all companies want the whole spec.
For example, the spec allows for brackets, and + aliases. I've worked at places that do not allow these, and some that allow aliases only for employees. Vest can't assume these decisions for you.

Making any sort of decision on these matters from Vest's side means leaving some cases unhandled, or even worse - adding more configuration and bloat that people won't need.

The compromise is simple. Vest supports extending the built-in enforcements by using `enforce.extend`. One of the most recommended ways of adding custom email validations is using the excellent `validator` package for adding those business specific validations.

https://vestjs.dev/#/./n4s/external?id=consuming-external-rules

```js
import isEmail from 'validator/es/lib/isEmail';

enforce.extend({ isEmail });

enforce('example@example.com').isEmail(); // ✅
enforce('example[at]example[dot]com').isEmail(); // 🚨
```

--

Regarding project support, there are quite a few things possible at the moment, but most opportunities will open up soon.
I am working on the fourth major version of Vest which will introduce some internal changes, and following the release I will open up more issues. At the moment I try not to add new issues to not introduce conflicting changes.

Some things that do can be done in the meantime:
- Improving test coverage
- Adding a reactive interface to Vest, possibly a wrapper.
- Improving the overall documentation.

If any of these interests you, let's talk :)

Thanks!

**Comment by martygo** [comment]
Thank you for your feedback.

I'm currently starting a teaching project on Youtube on the Vue ecosystem
and in my research I found Vest. The Vest is simply wonderful, simple and
sensational. I will start recommending to the current team of the company I
work for and to my subscribers on youtube.

Congratulations on the project.

Em sex., 22 de out. de 2021 às 13:20, Evyatar ***@***.***>
escreveu:

**Comment by martygo** [comment]
English is not my native one, I'm still learning and contributing to the
documentation of this project, it would only get in the way of helping 😁

Em sex., 22 de out. de 2021 às 13:32, Martins Gouveia <
***@***.***> escreveu:
