### ISSUE TITLE
Module '"vest"' has no exported member 'skipWhen'

### ISSUE THREAD

**Issue by RobMaple** [ealush/vest#720]
I'm seeing a typescript error in VSCode when trying to use the 'skipWhen' function. 

`import { create, test, enforce, skipWhen, group } from 'vest';`

Had a quick look in the code base and seems theres no type annotations in hte skipWhen file? Should this be the case or should the module be imported differently?

**Comment by ealush** [comment]
Hey @RobMaple, thank you for this issue.
I am very sorry. I recently made a change related to skipWhen for forward compatibility with version 4, and forgot to add the appropriate types.

I now released a patch with the types for skipWhen. You can install `vest@3.2.8` to use it.

Again, sorry for the hassle!

**Comment by RobMaple** [comment]
Hey @ealush, thanks for looking at this so quickly! No need to appologies though, just an observation I made that though might be worth reporting.
