### ISSUE TITLE
Add new rule `isKeyOf`

### ISSUE THREAD

**Issue by ealush** [ealush/vest#757]
Add a new rule that checks whether a value is a key of an object.

```js
enforce("bananas").isKeyOf({
	apples: 5,
	bananas: 2,
  	cantelopes: 0,
});
```

It should pass if the value passed to enforce is a key in the passed object.

To start:

1. Add the new rule file under https://github.com/ealush/vest/tree/latest/packages/n4s/src/rules
2. Add tests for that rule under https://github.com/ealush/vest/tree/latest/packages/n4s/src/rules/__tests__
3. Reference and export that rule here https://github.com/ealush/vest/blob/latest/packages/n4s/src/runtime/rules.ts

**Comment by galezra** [comment]
I'll take that :)

**Comment by ealush** [comment]
Awesome. Let me know if you need anything from me
