### ISSUE TITLE
[Documentation] Cannot scroll some pages / Chrome

### ISSUE THREAD

**Issue by pbowyer** [ealush/vest#791]
Bit of a weird one in Chrome 98 on Windows 10 (tested in Normal and Incognito modes).

On certain pages (this is not all, just a sampling)
- https://vestjs.dev/docs/understanding_state
- https://vestjs.dev/docs/writing_your_suite/including_and_excluding/skip_and_only
- https://vestjs.dev/docs/concepts
- https://vestjs.dev/docs/writing_your_suite/including_and_excluding/omitWhen
- https://vestjs.dev/docs/writing_tests/using_the_test_function
I cannot scroll down the page using mouse or keyboard.

https://user-images.githubusercontent.com/89852/154028269-a905e44a-82f5-41b2-9c22-11d736a32176.mp4

This page though scrolls fine
- https://vestjs.dev/docs/writing_your_suite/including_and_excluding/include

And they scroll in Firefox.

**Comment by ealush** [comment]
Ooh. That's a weird one. I am using docosaurus with a pretty minimal setup, so I am not sure what it could be. I do not experience it myself, which makes me wonder:
1. Does it happen consistently every time you reload these pages?
2. Are there any js errors displayed in the console?
3. Could it be some chrome extension interfering with scroll position?

Thanks for reporting that!
